### ISSUE TITLE
No scrollbar in Firefox v54.0 on Ubuntu

### ISSUE THREAD

**Issue by sierkje** [evbogue/minbase#1] opened 2017-08-16 01:27 UTC
Removing `overflow-y: hidden` from the `.screen` class* makes the scrollbar appear for me.

(*see https://github.com/evbogue/minbase/blob/master/style.css line 42)

**Comment by evbogue** [comment] 2017-08-16 20:08
@sierkje I've confirmed that pull-scroll is not working in Firefox and opened an issue on https://github.com/dominictarr/pull-scroll/

Removing `overflow-y` shows the scroller, however the scroller stops loading content at the point, so that isn't quite the fix. I'll mess around with it and see if I can figure out what is going wrong.

**Comment by evbogue** [comment] 2017-08-18 01:38
@sierkje This issue should be resolved with 7b07338f2c3a97c56f4a111cfa8f351c6aef0007

It turns out I had commented out some magic.

**Comment by evbogue** [comment] 2017-09-02 22:41
I think this is resolved.

**Closed by evbogue** 2017-09-02 22:41 UTC
